---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
title: Turtle Race!
description: Race turtles against each other!
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Race track
  completion:
  - engaged
- title: 'Challenge: More lines'
- title: Racing turtles
  completion:
  - internal
  - external
